[package]
edition = "2021"
name    = "ucs01-relay-api"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
cosmwasm-schema   = { workspace = true }
cosmwasm-std      = { workspace = true, features = ["stargate"] }
ethabi            = { workspace = true }
thiserror         = { workspace = true }
token-factory-api = { workspace = true }
