[package]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "hubble"
publish      = false
repository   = { workspace = true }
version      = "0.1.0"

[lints]
workspace = true

[package.metadata.crane]
include = [".sqlx"]

[[bin]]
name = "hubble"
path = "src/main.rs"

[dependencies]
axum               = { workspace = true, features = ["macros", "tokio"] }
base64             = "0.21.5"
clap               = { workspace = true, features = ["derive", "env"] }
color-eyre         = { workspace = true, features = ["default"] }
ethers             = { workspace = true, features = ["default", "std"] }
futures            = { workspace = true, features = ["async-await"] }
graphql_client     = { version = "0.13.0", features = ["reqwest-rustls", "reqwest", "reqwest-blocking"] }
lazy_static        = { workspace = true }
prometheus         = { version = "0.13.3", features = ["process"] }
reqwest            = { workspace = true, features = ["json", "blocking"] }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
sqlx               = { workspace = true, features = ["postgres", "runtime-tokio", "tls-rustls", "time", "macros", "json"] }
tendermint         = { workspace = true, features = ["std"] }
tendermint-rpc     = { workspace = true, features = ["http-client", "tokio"] }
time               = { version = "0.3.30", features = ["serde"] }
tokio              = { workspace = true, features = ["full"] }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url                = { version = "2.4.1", features = ["serde"] }
valuable           = { version = "0.1.0", features = ["derive"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
