[package]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "hubble"
publish      = false
repository   = { workspace = true }
version      = "0.1.0"

[package.metadata.crane]
include = ["hubble/src/graphql/", ".sqlx"]

[lib]
name = "hubble"
path = "src/lib.rs"

[[bin]]
name = "hubble"
path = "src/main.rs"

[dependencies]
axum               = { workspace = true, features = ["macros", "tokio"] }
clap               = { workspace = true, features = ["derive", "env"] }
color-eyre         = { workspace = true, features = ["default"] }
futures            = { workspace = true }
graphql_client     = { version = "0.13.0", features = ["reqwest-rustls", "reqwest", "reqwest-blocking"] }
lazy_static        = { workspace = true }
prometheus         = { version = "0.13.3", features = ["process"] }
reqwest            = { workspace = true, features = ["json", "blocking"] }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
sqlx               = { workspace = true, features = ["postgres", "runtime-tokio", "tls-rustls", "time", "macros", "json"] }
tendermint         = { workspace = true, features = ["std"] }
tendermint-rpc     = { workspace = true, features = ["http-client", "tokio"] }
time               = { version = "0.3.30", features = ["serde"] }
tokio              = { workspace = true, features = ["full"] }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
url                = { version = "2.4.1", features = ["serde"] }
