[package]
name = "unionvisor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive", "env"] }
color-eyre = "0.5"
figment = { version = "0.10.8", features = ["toml", "json"] }
fs_extra = "1.3.0"
reqwest = { version = "0.11.17", features = ["blocking"] }
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
toml = "0.7.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3.17", features = ["json", "tracing-log"] }

[dev-dependencies]
tempfile = "3.5.0"
tracing-test =  "0.2.4"
