[package]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "zerg"
publish      = false
repository   = { workspace = true }
version      = "0.1.0"

[package.metadata.crane]
include = []

[dependencies]
block-message.workspace = true
chain-utils             = { workspace = true }
clap                    = { workspace = true, features = ["default", "derive", "env", "error-context"] }
contracts               = { workspace = true }
cosmwasm-std            = { workspace = true, features = ["stargate", "ibc3", "cosmwasm_1_3"] }
csv                     = "1.3.0"
ethers                  = { workspace = true, features = ["rustls", "ws"] }
futures                 = { workspace = true }
queue-msg.workspace     = true
serde                   = { workspace = true, features = ["derive"] }
serde-utils             = { workspace = true }
serde_json              = { workspace = true }
tendermint              = { workspace = true }
tendermint-proto        = { workspace = true }
tendermint-rpc          = { workspace = true, features = ["http-client", "websocket-client"] }
tokio                   = { workspace = true, features = ["macros"] }
tokio-stream            = { workspace = true }
tonic                   = { workspace = true, features = ["transport", "tls", "tls-roots", "tls-webpki-roots"] }
tracing                 = { workspace = true }
tracing-subscriber      = { workspace = true, features = ["env-filter"] }
ucs01-relay             = { workspace = true, features = ["library"] }
ucs01-relay-api         = { workspace = true }
unionlabs               = { workspace = true, features = ["ethabi"] }
uuid                    = { version = "1.5.0", features = ["serde", "v4"] }
