[workspace]
members = [
  "lib/*",
  "lib/*/fuzz",
  "light-clients/ethereum-light-client",
  "light-clients/cometbls-light-client",
  "generated/rust",
  "generated/contracts",
  "unionvisor",
  "voyager",
  "cosmwasm/*",
  "hubble"
]

exclude = [
  "tools/generate-rust-sol-bindings",
  "e2e/ensure-blocks",
]

resolver = "2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = true

[workspace.dependencies]

# ssz
# cspell:disable-next-line (isnt)
ssz = { package = "ethereum_ssz", git = "https://github.com/unionlabs/ethereum_ssz", branch = "vec-isnt-valid-ssz", default-features = false }
ssz_types = { git = "https://github.com/unionlabs/ssz_types", branch = "try-from-instead-of-from", default-features = false }
tree_hash = { git = "https://github.com/unionlabs/tree_hash", branch = "use-unionlabs-ssz", default-features = false }

milagro_bls = { git = "https://github.com/datachainlab/milagro_bls", rev = "bc2b5b5e8d48b7e2e1bfaa56dc2d93e13cb32095", default-features = false }

contracts = { path = "generated/contracts", default-features = false }
serde-utils = { path = "lib/serde-utils", default-features = false }
pg-queue = { path = "lib/pg-queue", default-features = false }
ethereum-verifier = { path = "lib/ethereum-verifier", default-features = false }
cometbls-groth16-verifier = { path = "lib/cometbls-groth16-verifier", default-features = false }
ics008-wasm-client = { path = "lib/ics-008-wasm-client", default-features = false }
protos = { path = "generated/rust", default-features = false }
unionlabs = { path = "lib/unionlabs", default-features = false }
beacon-api = { path = "lib/beacon-api", default-features = false }
chain-utils = { path = "lib/chain-utils", default-features = false }
hubble = { path = "hubble" }

tendermint = { git = "https://github.com/unionlabs/tendermint-rs", branch = "bn254", default-features = false }
tendermint-proto = { git = "https://github.com/unionlabs/tendermint-rs", branch = "bn254", default-features = false }
tendermint-rpc = { git = "https://github.com/unionlabs/tendermint-rs", branch = "bn254", default-features = false }

token-factory-api = { path = "cosmwasm/token-factory-api", default-features = false }
ucs01-relay-api = { path = "cosmwasm/ucs01-relay-api", default-features = false }

[patch.crates-io]
typenum = { git = "https://github.com/unionlabs/typenum", branch = "ben/192-const-generic-32-bit" }
