[workspace]
members = [
  "lib/*",
  "light-clients/ethereum-light-client",
  "light-clients/wasm-light-client-types",
  "generated/rust",
  "generated/contracts",
  "unionvisor",
  "relayer",
  "cosmwasm/*"
]

exclude = [
  "tools/generate-rust-sol-bindings"
]

resolver = "2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = true
