[profile.default]
optimizer = true
optimizer_runs = 20000
via_ir = true

cache = true
cache_path = "evm/cache"

src = "evm/contracts"
libs = ["evm/lib", "evm/node_modules"]
test = "evm/tests/src"
out = "evm/out"

gas_reports = ["*"]