[profile.default]
optimizer = true
optimizer_runs = 20000
via_ir = true

cache = true
cache_path = "evm/cache"

src = "evm/contracts"
libs = ["evm/tests/foundry/lib", "evm/tests/node_modules"]
out = "evm/out"
test = "evm/tests/foundry/src"

gas_reports = ["*"]