version: "0.5"

processes:
  devnet-union:
    command: nix run .#devnet-union
    log_location: ./.devnet/logs/devnet-union.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/block?height=2"
        port: 26657
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 60
    shutdown:
      signal: 2
  devnet-osmosis:
    command: nix run .#devnet-osmosis
    log_location: ./.devnet/logs/devnet-osmosis.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/block?height=2"
        port: 26857
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 60
    shutdown:
      signal: 2
  voyager-queue:
    command: nix run .#voyager-queue -L
    log_location: ./.devnet/logs/voyager-queue.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    readiness_probe:
      exec:
        command: "pg_isready -h 127.0.0.1 -p 5432 -d default -U postgres"
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 60
    shutdown:
      signal: 2
  voyager-migrations:
    command: RUST_LOG=debug nix run -L github:unionlabs/union/voyager-channel-creation#voyager -- -c ./voyager-config.json run-migrations
    availability:
      restart: "on_failure"
      backoff_seconds: 2
    depends_on:
      voyager-queue:
        condition: process_healthy
    log_location: ./.devnet/logs/voyager-migrations.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    shutdown:
      signal: 2
  voyager-relay:
    command: RUST_LOG=info nix run -L github:unionlabs/union/voyager-channel-creation#voyager -- -c ./voyager-config.json relay
    availability:
      restart: "always"
      backoff_seconds: 2
    depends_on:
      voyager-migrations:
        condition: process_completed_successfully
    log_location: ./.devnet/logs/voyager-relay.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    shutdown:
      signal: 2
  voyager-handshake:
    command: nix run -L github:unionlabs/union/voyager-channel-creation#voyager -- -c ./voyager-config.json handshake union-devnet osmosis-devnet --client-a-config null --client-b-config '{"checksum":"0xb4c67f099d011e68ec6954b4406d5b8f59b87b57e84d3cd11c69c1f52d8d876c"}' --port-a "wasm.union15z28y43vjqps24gcsamlrlur87phnkd974ucemzkzny59waxhxsqzmx5j7" --port-b "wasm.wasm15z28y43vjqps24gcsamlrlur87phnkd974ucemzkzny59waxhxsqur547e" --channel-version "ucs00-pingpong-1" --channel-ordering ordered --connection-ordering ordered --create-clients --open-connection --open-channel --init-fetch
    depends_on:
      voyager-migrations:
        condition: process_completed_successfully
      devnet-union: 
        condition: process_healthy
      devnet-osmosis: 
        condition: process_healthy
    shutdown:
      signal: 2
  download-circuit:
    command: nix run ".#download-circuit-devnet" . 
    log_location: ./.devnet/logs/download-circuit.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    shutdown:
      signal: 2
  galois:
    command: nix run .#galoisd -- serve localhost:9999 --cs-path=.devnet/circuit/r1cs.bin --pk-path=.devnet/circuit/pk.bin --vk-path=.devnet/circuit/vk.bin
    log_location: ./.devnet/logs/galois.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    depends_on:
      download-circuit:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        command: "nix run .#galoisd -- query-stats localhost:9999"
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 60
    shutdown:
      signal: 2


log_configuration:
  disable_json: true
  no_metadata: true  
