{
  "version": "0.5",
  "log_location": ".devnet/logs/",
  "log_configuration": {
    "disable_json": true,
    "no_color": false,
    "no_metadata": true,
    "add_timestamp": false,
    "flush_each_line": false
  },
  "log_format": "plain",
  "processes": {
    "union-devnet": {
      "name": "Union Devnet",
      "command": "nix run .#devnet-union",
      "readiness_probe": {
        "http_get": {
          "host": "127.0.0.1",
          "path": "/block?height=2",
          "scheme": "http",
          "port": 26657
        },
        "initial_delay_seconds": 10,
        "period_seconds": 10,
        "timeout_seconds": 5,
        "success_threshold": 1,
        "failure_threshold": 1000
      }
    }
  },
  "is_strict": true
}