{
  "version": "0.5",
  "log_location": ".devnet/logs/",
  "log_configuration": {
    "disable_json": true,
    "no_color": false,
    "no_metadata": true,
    "add_timestamp": false,
    "flush_each_line": false
  },
  "log_format": "plain",
  "processes": {
    "union-devnet": {
      "name": "Union Devnet",
      "command": "nix run .#devnet-union"
    }
  },
  "is_strict": true
}