version: "0.5"

processes:
  devnet-union:
    command: nix run .#devnet-union
    log_location: ./.devnet/logs/devnet-union.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/block?height=2"
        port: 26657
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 600
    shutdown:
      signal: 2
  devnet-osmosis:
    command: nix run .#devnet-osmosis
    log_location: ./.devnet/logs/devnet-osmosis.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/block?height=2"
        port: 26857
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 600
    shutdown:
      signal: 2
  voyager-queue:
    command: nix run .#voyager-queue -L
    log_location: ./.devnet/logs/voyager-queue.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    readiness_probe:
      exec:
        command: "pg_isready -h 127.0.0.1 -p 5432 -d default -U postgres"
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 600
    shutdown:
      signal: 2
  voyager-migrations:
    command: RUST_LOG=debug nix run -L .#voyager -- -c ./voyager-config.json run-migrations
    availability:
      restart: "on_failure"
      backoff_seconds: 2
    depends_on:
      voyager-queue:
        condition: process_healthy
    log_location: ./.devnet/logs/voyager-migrations.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    shutdown:
      signal: 2
  voyager-relay:
    command: RUST_LOG=info nix run -L .#voyager -- -c ./voyager-config.json relay
    availability:
      restart: "always"
      backoff_seconds: 2
    depends_on:
      devnet-union: 
        condition: process_healthy
      devnet-osmosis: 
        condition: process_healthy
      voyager-migrations:
        condition: process_completed_successfully
    log_location: ./.devnet/logs/voyager-relay.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/health"
        port: 65534
      initial_delay_seconds: 0
      period_seconds: 1
      timeout_seconds: 1
      success_threshold: 1
      failure_threshold: 600
    shutdown:
      signal: 2
  voyager-client-connection-handshake:
    command: set -o pipefail; nix run .#voy-send-msg -- $(nix run -L .#voyager -- -c ./voyager-config.json handshake union-devnet osmosis-devnet --client-a-config null --client-b-config '{"checksum":"0xb2785dc632f285c14aad784c5f19046e5d1558ff3a7961c3a1863b2c89166117"}' --create-clients --open-connection --connection-ordering unordered --init-fetch)
    log_location: ./.devnet/logs/voyager-client-connection-handshake.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    depends_on:
      voyager-migrations:
        condition: process_completed_successfully
      devnet-union: 
        condition: process_healthy
      devnet-osmosis: 
        condition: process_healthy
      voyager-relay: 
        condition: process_healthy
    readiness_probe:
      exec:
        command: set -o pipefail; nix run .#uniond --  query ibc client states --node http://localhost:26657 | yq -e '.client_states[] | select(.client_id == "07-tendermint-0")' 
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 600
    shutdown:
      signal: 2
  download-circuit:
    command: nix run ".#download-circuit-devnet" . 
    log_location: ./.devnet/logs/download-circuit.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    shutdown:
      signal: 2
  galois:
    command: nix run .#galoisd -- serve localhost:9999 --cs-path=.devnet/circuit/r1cs.bin --pk-path=.devnet/circuit/pk.bin --vk-path=.devnet/circuit/vk.bin
    log_location: ./.devnet/logs/galois.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    depends_on:
      download-circuit:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        command: "nix run .#galoisd -- query-stats localhost:9999"
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 600
    shutdown:
      signal: 2


log_configuration:
  disable_json: true
  no_metadata: true  
