{
  "version": "0.5",
  "log_location": "./.devnet/logs/",
  "log_configuration": {
    "rotation": {
      "directory": "./.devnet/logs/",
      "compress": false
    },
    "disable_json": true,
    "no_color": false,
    "no_metadata": true,
    "add_timestamp": false,
    "flush_each_line": false
  },
  "log_format": "plain",
  "processes": {
    "devnet-union": {
      "name": "Union Devnet",
      "command": "nix run .#devnet-union",
      "log_configuration": {
        "disable_json": true,
        "no_metadata": true,
        "add_timestamp": false
      },
      "log_location": "./.devnet/logs//devnet-union.log",
      "readiness_probe": {
        "http_get": {
          "host": "127.0.0.1",
          "path": "/block?height=2",
          "scheme": "http",
          "port": 26657
        },
        "initial_delay_seconds": 10,
        "period_seconds": 10,
        "timeout_seconds": 5,
        "success_threshold": 1,
        "failure_threshold": 1000
      }
    },
    "devnet-osmosis": {
      "name": "Osmosis Devnet",
      "command": "nix run .#devnet-osmosis",
      "log_configuration": {
        "disable_json": true,
        "no_metadata": true,
        "add_timestamp": false
      },
      "log_location": "./.devnet/logs//devnet-osmosis.log",
      "readiness_probe": {
        "http_get": {
          "host": "127.0.0.1",
          "path": "/block?height=2",
          "scheme": "http",
          "port": 26857
        },
        "initial_delay_seconds": 10,
        "period_seconds": 10,
        "timeout_seconds": 5,
        "success_threshold": 1,
        "failure_threshold": 1000
      }
    },
    "devnet-stargaze": {
      "name": "Stargaze Devnet",
      "command": "nix run .#devnet-stargaze",
      "log_configuration": {
        "disable_json": true,
        "no_metadata": true,
        "add_timestamp": false
      },
      "log_location": "./.devnet/logs//devnet-stargaze.log",
      "readiness_probe": {
        "http_get": {
          "host": "127.0.0.1",
          "path": "/block?height=2",
          "scheme": "http",
          "port": 26757
        },
        "initial_delay_seconds": 10,
        "period_seconds": 10,
        "timeout_seconds": 5,
        "success_threshold": 1,
        "failure_threshold": 1000
      }
    }
  },
  "is_strict": true
}