{
  "version": "0.5",
  "log_location": "./.devnet/logs/",
  "log_configuration": {
    "rotation": {
      "directory": "./.devnet/logs/",
      "compress": false
    },
    "disable_json": true,
    "no_color": false,
    "no_metadata": true,
    "add_timestamp": false,
    "flush_each_line": false
  },
  "log_format": "plain",
  "processes": {
    "connection-union-osmosis": {
      "name": "connection-union-osmosis",
      "is_daemon": true,
      "command": "set -o pipefail; nix run .#voy-send-msg -- $(nix run -L .#voyager -- -c ./voyager-config.json handshake union-devnet osmosis-devnet --client-a-config null --client-b-config '{\"checksum\":\"0xb2785dc632f285c14aad784c5f19046e5d1558ff3a7961c3a1863b2c89166117\"}' --create-clients --open-connection --connection-ordering unordered --init-fetch)",
      "log_configuration": {
        "disable_json": true,
        "no_metadata": true,
        "add_timestamp": false
      },
      "log_location": "./.devnet/logs/connection-union-osmosis.log",
      "depends_on": {
        "devnet-union": {
          "condition": "process_healthy"
        },
        "devnet-osmosis": {
          "condition": "process_healthy"
        },
        "voyager-migrations": {
          "condition": "process_completed_successfully"
        }
      },
      "shutdown": {
        "signal": 2
      }
    },
    "devnet-osmosis": {
      "name": "devnet-osmosis",
      "command": "nix run .#devnet-osmosis",
      "log_configuration": {
        "disable_json": true,
        "no_metadata": true,
        "add_timestamp": false
      },
      "log_location": "./.devnet/logs/devnet-osmosis.log",
      "readiness_probe": {
        "http_get": {
          "host": "127.0.0.1",
          "path": "/block?height=2",
          "scheme": "http",
          "port": 26857
        },
        "initial_delay_seconds": 10,
        "period_seconds": 10,
        "timeout_seconds": 5,
        "success_threshold": 1,
        "failure_threshold": 1000
      },
      "shutdown": {
        "signal": 2
      }
    },
    "voyager-queue": {
      "name": "voyager-queue",
      "command": "nix run .#voyager-queue -L",
      "log_configuration": {
        "disable_json": true,
        "no_metadata": true,
        "add_timestamp": false
      },
      "log_location": "./.devnet/logs/voyager-queue.log",
      "readiness_probe": {
        "exec": {
          "command": "pg_isready -h 127.0.0.1 -p 5432 -d default -U postgres"
        },
        "initial_delay_seconds": 5,
        "period_seconds": 10,
        "timeout_seconds": 5,
        "success_threshold": 1,
        "failure_threshold": 1000
      },
      "shutdown": {
        "signal": 2
      }
    },
    "devnet-union": {
      "name": "devnet-union",
      "command": "nix run .#devnet-union",
      "log_configuration": {
        "disable_json": true,
        "no_metadata": true,
        "add_timestamp": false
      },
      "log_location": "./.devnet/logs/devnet-union.log",
      "readiness_probe": {
        "http_get": {
          "host": "127.0.0.1",
          "path": "/block?height=2",
          "scheme": "http",
          "port": 26657
        },
        "initial_delay_seconds": 10,
        "period_seconds": 10,
        "timeout_seconds": 5,
        "success_threshold": 1,
        "failure_threshold": 1000
      },
      "shutdown": {
        "signal": 2
      }
    },
    "galoisd": {
      "name": "galoisd",
      "command": "nix run .#galoisd -- serve localhost:9999 --cs-path=./.devnet/circuit/r1cs.bin --pk-path=./.devnet/circuit/pk.bin --vk-path=./.devnet/circuit/vk.bin",
      "log_configuration": {
        "disable_json": true,
        "no_metadata": true,
        "add_timestamp": false
      },
      "log_location": "./.devnet/logs/galoisd.log",
      "depends_on": {
        "galois-download-circuit": {
          "condition": "process_completed_successfully"
        }
      },
      "readiness_probe": {
        "exec": {
          "command": "nix run .#galoisd -- query-stats localhost:9999"
        },
        "initial_delay_seconds": 5,
        "period_seconds": 10,
        "timeout_seconds": 5,
        "success_threshold": 1,
        "failure_threshold": 1000
      },
      "shutdown": {
        "signal": 2
      }
    },
    "voyager-migrations": {
      "name": "voyager-migrations",
      "command": "RUST_LOG=debug nix run -L .#voyager -- -c ./voyager-config.json run-migrations",
      "log_configuration": {
        "disable_json": true,
        "no_metadata": true,
        "add_timestamp": false
      },
      "log_location": "./.devnet/logs/voyager-migrations.log",
      "depends_on": {
        "voyager-queue": {
          "condition": "process_healthy"
        }
      },
      "shutdown": {
        "signal": 2
      }
    },
    "galois-download-circuit": {
      "name": "galois-download-circuit",
      "command": "nix run .#download-circuit-devnet .",
      "log_configuration": {
        "disable_json": true,
        "no_metadata": true,
        "add_timestamp": false
      },
      "log_location": "./.devnet/logs/galois-download-circuit.log",
      "readiness_probe": {
        "exec": {
          "command": "nix run .#galoisd -- query-stats localhost:9999"
        },
        "initial_delay_seconds": 5,
        "period_seconds": 10,
        "timeout_seconds": 5,
        "success_threshold": 1,
        "failure_threshold": 1000
      },
      "shutdown": {
        "signal": 2
      }
    }
  },
  "is_strict": true
}