[[chain]]
name = "evm"
ibc-handler-address = ""

	[[chain.client]]
	type = "cometbls"
	client-id = ""
	cometbls-client-address = ""

		[[chain.client.connections]]
		counterparty = { chain = "cosmos", client-id = "" }

			[[chain.client.connections.channels]]
			port = "transfer"
			ics20-transfer-address = ""


[[chain]]
name = "cosmos"
code-id = ""

[[client]]
chain = "cosmos"
type = "ethereum"



[[connection]]

	[[connection.chain-a]]
	chain = "evm"
	client = "cometbls-0"

	[[connection.chain-b]]
	chain = "cosmos"
	client = "08-wasm-0"


[[channel]]

	[[channel.chain-a]]
	chain = "evm"
	connection = "connection-0"
	port = "transfer"
	ics20-transfer-address = ""

	[[channel.chain-b]]
	chain = "cosmos"
	connection = "connection-0"
	# wasm.contract-address
	port = ""




