[build]
publish = "dist"
ignore  = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./site/"
command = "git lfs pull &&  npm_config_yes=true npx astro@latest start"

[[plugin]]
package = "@netlify/plugin-lighthouse"
