
[package]
edition    = { workspace = true }
name       = "contracts"
publish    = false
repository = { workspace = true }
version    = "0.0.0"

[lints]
workspace = true

[dependencies]
arbitrary = { workspace = true, optional = true, features = ["derive"] }
ethers    = { workspace = true }
serde     = { workspace = true, features = ["derive"] }
[features]
arbitrary = ["dep:arbitrary"]
providers = ["ethers/providers"]
