[language-server.astro-ls]
args    = ["@astrojs/language-server", "--stdio"]
command = "npx"
config  = { "typescript" = { "tsdk" = "./site/node_modules/typescript/lib" }, "environment" = "node" }

[[language]]
file-types       = ["astro"]
injection-regex  = "astro"
language-servers = ["astro-ls"]
name             = "astro"
roots            = ["package.json", "astro.config.ts"]
scope            = "source.astro"
