[package]
name = "cometbls-light-client"
version = "0.1.0"
authors = ["Union Labs"]
edition = "2021"
publish = false
license = "BSL-1.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes = { version = "1.2.1", default-features = false }
cosmwasm-std = { version = "1.3.0", default-features = false, features = ["abort"] }
hex = { version = "0.4", default-features = false }
prost = { version = "0.11", default-features = false }
schemars = { version = "0.8.3", default-features = false }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
serde-json-wasm = { version = "*", default-features = false }
sha3 = { version = "0.10.8", default-features = false }
sha2 = { version = "0.10.8", default-features = false }
ripemd = { version = "0.1.3", default-features = false }
thiserror = { version = "1.0.26", default-features = false }
protos = { workspace = true, default-features = false, features = ["proto_full", "std"] }
cometbls-groth16-verifier = { workspace = true, default-features = false }

ics008-wasm-client.workspace = true
unionlabs = { workspace = true, default-features = false }
ics23.workspace = true

[dev-dependencies]
base64 = "0.21"
serde_json = "1"

[features]
