[package]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "cargo-workspace-dependencies"
publish      = false
repository   = { workspace = true }
version      = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-util-schemas = "0.1.0"
cargo_metadata     = "0.18.1"
clap               = { workspace = true, features = ["derive", "default"] }
toml               = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt"] }
