[package]
name = "devnet-compose"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
serde                     = { workspace = true, features = ["derive", "std"] }
serde_json.workspace = true
serde_with = { workspace = true, features = ["macros", "json"] }
strum = {version = "0.26.2", features = ["derive"] }

[lints]
workspace = true
