[workspace]
members = [
  "ethereum",
  "08-wasm"
]
exclude = [
  "ethereum-light-client-rs" 
]
resolver = "2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = true