[package]
name = "voyager"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
bech32 = "0.9.1"
bip32 = { version = "0.5.0", features = ["secp256k1"] }
ethers = { version = "2.0.4", features = ["rustls", "ws"] }
futures = "0.3.28"
hex-literal = "0.4.1"
num-bigint = "0.4"
prost = "0.11.0"
reqwest = { version = "0.11.17", default-features = false, features = ["tokio-rustls"] }
ripemd = "0.1.3"
serde_json = "1.0.96"
sha2 = "0.10.6"
subtle-encoding = { version = "0.5.1", features = ["bech32-preview"] }
tendermint = { workspace = true }
tendermint-proto = { workspace = true }
tendermint-rpc = { workspace = true, features = ["http-client", "websocket-client"] }
tokio = { version = "1.27.0", features = ["macros"] }
tonic = { version = "0.9", features = ["transport","tls","tls-roots","tls-webpki-roots"] }
tower = { version = "*", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.3.0", features = ["derive", "env", "error-context"] }
tracing = "0.1.37"
typenum = "1.16.0"
serde = { version = "1.0.173", features = ["derive"] }
hex = { version = "0.4.3", features = [ "serde" ] }
anyhow = "1.0.72"
pin-utils = "0.1.0"
tokio-stream = { version = "0.1.14" }
either = { version = "1.9.0", features = ["serde"] }
pg-queue.workspace = true

beacon-api = { workspace = true, default-features = false }
contracts.workspace = true
protos = { workspace = true, features = ["proto_full", "client"] }
unionlabs = { workspace = true, features = ["ethabi"] }
ethereum-verifier.workspace = true
serde-utils.workspace = true
chain-utils.workspace = true
axum = { version = "0.6.20", features = ["macros"] }
frunk = "0.4.2"
bitvec = "1.0.1"
displaydoc = { version = "0.2.4", default-features = false }
frame-support-procedural = "18.0.0"
hubble.workspace = true
sqlx = { version = "0.7.2", features = ["postgres"] }
thiserror = "1.0.49"
crossbeam-queue = "0.3.8"
derive_more = "0.99.17"

[features]
eth-mainnet = [ "unionlabs/eth-mainnet" ]

[dev-dependencies]
csv = "1.3.0"
