[package]
name = "ucs01-relay"
version = "1.0.1"
authors = ["Hussein Ait Lahcen <hussein.aitlahcen@gmail.com>"]
edition = "2021"
repository = "https://github.com/unionlabs/union"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
ethabi = { version = "18.0.0", default-features = false }
cosmwasm-schema = { version = "1.3" }
cw-utils = { version = "1.0.1" }
cw2 = { version = "1.1" }
cw20 = { version = "1.1" }
cw-controllers = { version = "1.1" }
cw-storage-plus = { version = "1.1" }
cosmwasm-std = { version = "1.3", features = ["stargate"] }
schemars = "0.8"
semver = "1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
