[package]
authors      = ["Hussein Ait Lahcen <hussein.aitlahcen@gmail.com>"]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "ucs01-relay"
publish      = false
repository   = { workspace = true }
version      = "1.0.1"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-schema   = { workspace = true }
cosmwasm-std      = { workspace = true, features = ["stargate", "ibc3", "cosmwasm_1_3"] }
cw-controllers    = { version = "1.1" }
cw-storage-plus   = { workspace = true }
cw2               = { version = "1.1" }
dlmalloc          = { workspace = true, features = ["global"] }
ethabi            = { workspace = true }
hex               = { workspace = true }
schemars          = { workspace = true }
semver            = "1"
serde             = { workspace = true, features = ["derive"] }
sha2              = { workspace = true }
thiserror         = { workspace = true }
token-factory-api = { workspace = true }
ucs01-relay-api   = { workspace = true }
