[package]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "generate-rust-sol-bindings"
publish      = false
repository   = { workspace = true }
version      = "0.1.0"

[lints]
workspace = true

[dependencies]
clap                   = { workspace = true, features = ["default", "derive"] }
ethers-contract-abigen = { workspace = true, features = ["default", "fs"] }
