[package]
name = "generate-rust-sol-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
ethers-contract-abigen = { workspace = true, default-features = true, features = [ "fs" ] }
