[package]
name = "ucs00-pingpong"
version = "1.0.0"
authors = ["Hussein Ait Lahcen <hussein.aitlahcen@gmail.com>"]
edition = "2021"
repository = "https://github.com/unionlabs/union"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
ethabi = { version = "18.0.0", default-features = false }
cosmwasm-schema = { version = "1.3" }
cosmwasm-std = { version = "1.3", features = ["stargate"] }
cw-storage-plus = { version = "1.1" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
