name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  fail-on-draft:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  site:
    if: github.event.pull_request.draft == false
    uses: unionlabs/workflows/.github/workflows/build.yml@8fdbd5d131725a503e1e8c7a415edf6726da25c5
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
      access-tokens: github.com=${{ secrets.GH_NIX_TOKEN }}
      org_token: ${{ secrets.GH_NIX_TOKEN }}
    with:
      eval_target: 'site'
      eval_top_attr: 'packages'
      lfs: true
