name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  fail-on-draft:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  packages:
    if: github.event.pull_request.draft == false
    uses: unionlabs/workflows/.github/workflows/build.yml@485f5c3e76e23719e8283613375c13f87090a05e
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
      access-tokens: github.com=${{ secrets.GH_NIX_TOKEN }}
    with:
      eval_target: 'build'
      eval_top_attr: 'packages'
      lfs: true
  devShells:
    if: github.event.pull_request.draft == false
    uses: unionlabs/workflows/.github/workflows/build.yml@485f5c3e76e23719e8283613375c13f87090a05e
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
      access-tokens: github.com=${{ secrets.GH_NIX_TOKEN }}
    with:
      eval_target: 'dev'
      eval_top_attr: 'devShells'
      lfs: true
  checks:
    if: github.event.pull_request.draft == false
    uses: unionlabs/workflows/.github/workflows/build.yml@485f5c3e76e23719e8283613375c13f87090a05e
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
      access-tokens: github.com=${{ secrets.GH_NIX_TOKEN }}
    with:
      eval_target: 'test'
      eval_top_attr: 'checks'
      lfs: true
