name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  spell-fmt-check:
    runs-on: beefy-runner
    steps:
      - name: spell-fmt-check
        uses: unionlabs/workflows/.github/workflows/build.yml@b8a18e6f9742145ffd5b74ffe538462639478271
        secrets:
          nixbuild_token: ${{ secrets.nixbuild_token }}
          access-tokens: github.com=${{ secrets.GITHUB_TOKEN }}
        with:
          eval_target: 'spell-fmt'
          eval_top_attr: 'checks'
  build:
    runs-on: beefy-runner
    needs: [ spell-fmt-check ]
    steps:
      - name: build
        if: |
          !cancelled()
          && (contains(needs.*.result, 'success') || github.event.pull_request.draft == true)
        uses: unionlabs/workflows/.github/workflows/build.yml@b8a18e6f9742145ffd5b74ffe538462639478271
        secrets:
          nixbuild_token: ${{ secrets.nixbuild_token }}
          access-tokens: github.com=${{ secrets.GITHUB_TOKEN }}
        with:
          eval_target: 'build'
          eval_top_attr: 'packages'
  dev:
    runs-on: beefy-runner
    needs: [ spell-fmt-check ]
    steps:
      - name: dev
        if: |
          !cancelled()
          && (contains(needs.*.result, 'success') || github.event.pull_request.draft == true)
        uses: unionlabs/workflows/.github/workflows/build.yml@b8a18e6f9742145ffd5b74ffe538462639478271
        secrets:
          nixbuild_token: ${{ secrets.nixbuild_token }}
          access-tokens: github.com=${{ secrets.GITHUB_TOKEN }}
        with:
          eval_target: 'dev'
          eval_top_attr: 'devShells'
  test:
    runs-on: beefy-runner
    needs: [ spell-fmt-check ]
    if: |
      !cancelled()
      && (contains(needs.*.result, 'success') || github.event.pull_request.draft == true)
    steps:
      - name: test
        uses: unionlabs/workflows/.github/workflows/build.yml@b8a18e6f9742145ffd5b74ffe538462639478271
        secrets:
          nixbuild_token: ${{ secrets.nixbuild_token }}
          access-tokens: github.com=${{ secrets.GITHUB_TOKEN }}
        with:
          eval_target: 'test'
          eval_top_attr: 'checks'
          filter_builds: |
            (
              (.top_attr == "checks") and
              (.system == "x86_64-linux") and 
              ( 
                (
                  # Do not run
                  [.attr] | inside(
                    [
                      "treefmt-check"
                    ]
                  )
                ) | not
              )
            )
