name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    uses: unionfi/workflows/.github/workflows/build.yml@main
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
      access-tokens: github.com=${{ secrets.GITHUB_TOKEN }}
    with:
      filter_builds: '((.top_attr == "checks" or .top_attr == "packages") and (.system == "x86_64-linux" or .system == "aarch64-linux") and (.attr != "generate-evm-proto" and .attr != "generate-prover-proto" and .attr != "pre-commit-check" and .attr != "pre-commit" and .attr != "devnet")) or (.attr == "devnet" and .system == "x86_64-linux") or (.attr == "devnet-cosmos" and .system == "x86_64-linux") or (.attr == "devnet-evm" and .system == "x86_64-linux") or (.attr == "devnet" and .system == "x86_64-linux") and (.attr != "rust-proto") and (.attr != "generate-rust-proto")'