name: Links Checker

on:
  workflow_dispatch:
  repository_dispatch:
  # fail fast
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # daily check
  schedule:
    - cron: '00 18 * * *'

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  # runs on push and pull request
  link-checker:
    name: '🔗 Check Links'
    runs-on: ['ubuntu-latest']
    permissions:
      contents: read
      pull-requests: write
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Link Check
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: |
            'result/**/index.html'

      - name: Comment On Pull Request
        uses: actions/github-script@v7
        # only comment if there are errors and it's a pull request
        if: env.lychee_exit_code != 0 && github.event_name == 'pull_request'
        # temporarily allow this to fail until we're able to handle these two links: https://github.com/unionlabs/union/actions/runs/8014925873/attempts/1#summary-21894317581
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('node:fs');
            const content = fs.readFileSync('./lychee/out.md', { encoding: 'utf8' });
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: content
            });

  # runs once daily
  daily-link-checker:
    name: '🔗 Check Links'
    runs-on: ['ubuntu-latest']
    permissions:
      contents: read
      issues: write
    if: github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Link Check
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: |
            --no-progress
            'result/**/index.html'

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: |
            documentation
            dead-links
