name: Nightly

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 4 * * *'

jobs:
  load-secrets:
    runs-on: ubuntu-latest
    outputs:
      union-org-pat: ${{ steps.op-load-secret.UNION_ORG_PAT }}
      nixbuild-token: ${{ steps.op-load-secret.NIXBUILD_TOKEN }}
    steps:
      - name: Load Secrets
        id: op-load-secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env: 
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          UNION_ORG_PAT: op://ci/union-org-pat/pat
          NIXBUILD_TOKEN: op://ci/nixbuild-token/token

  build:
    needs: load-secrets
    uses: ./.github/workflows/e2e.yml
    secrets:
      nixbuild_token: ${{ needs.load-secrets.outputs.nixbuild-token }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
      org_token: ${{ needs.load-secrets.outputs.union-org-pat }}

  create-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    needs: [build]
    # only create an issue if it failed in a scheduled run
    if: github.event_name == 'schedule' && failure()
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: .github/templates/nightly-issue-template.md
