name: ReleaseCandidate

on:
  push:
    branches: [ fix-rc-pipeline ]
    # tags: ['v[0-9]+\.[0-9]+\.[0-9]+\-rc[0-9]+']

jobs:
  build:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v16
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
    with:
      filter_builds: '(.top_attr == "packages") and (.system == "x86_64-linux" or .system == "aarch64-linux") and (.attr == "uniond" or .attr == "uniond-image")' # ensure to append this list if you want to release more artifacts

  download-docker-images:
    runs-on: ubuntu-latest
    needs: [build]
    permissions: write-all
    strategy:
      matrix:
        package: [ uniond-image ]
        system: [ aarch64-linux, x86_64-linux ]
    steps: 
      - uses: actions/download-artifact@v3
        with:
          name: packages.${{ matrix.system }}.${{ matrix.package }}
      - uses: nixbuild/nix-quick-install-action@v22
      - uses: nixbuild/nixbuild-action@v17
        with:
          nixbuild_token: ${{ secrets.nixbuild_token }}
      - run: mkdir ${{ matrix.system }}
      - run: nix copy --to file://`pwd`/${{ matrix.system }} --from ssh-ng://eu.nixbuild.net `cat result.json | jq -r '.packages."${{ matrix.system }}"."${{ matrix.package }}".outputs.out'` --extra-experimental-features nix-command
      - run: cat ${{ matrix.system }}/nar/*.nar.xz | xz -dc | nix-store --restore ${{ matrix.system }}.${{ matrix.package }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.system }}.${{ matrix.package }}
          path: ${{ matrix.system }}.${{ matrix.package }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker load < ${{ matrix.system }}.uniond-image
      - run: docker tag `docker images -q uniond` ghcr.io/unionfi/uniond:${{ github.ref_name }}-${{ matrix.system }}
      - run: docker push ghcr.io/unionfi/uniond:${{ github.ref_name }}-${{ matrix.system }}

  download-static-binaries:
    runs-on: ubuntu-latest
    needs: [build]
    permissions: write-all
    strategy:
      matrix:
        package: [ uniond ]
        system: [ aarch64-linux, x86_64-linux ]
    steps: 
      - uses: actions/download-artifact@v3
        with:
          name: packages.${{ matrix.system }}.${{ matrix.package }}
      - uses: nixbuild/nix-quick-install-action@v22
      - uses: nixbuild/nixbuild-action@v17
        with:
          nixbuild_token: ${{ secrets.nixbuild_token }}
      - run: mkdir ${{ matrix.system }}
      - run: ls -la
      - run: ls -la ${{ matrix.system }}
      - run: |
          OUTPUT=`cat result.json | jq -r '.packages."${{ matrix.system }}"."${{ matrix.package }}".outputs.out'`
          prefix="/nix/store/"
          suffix="-uniond"
          trimmed=${OUTPUT#$prefix}
          trimmed=${trimmed%$suffix}
          NAR_NAME=$trimmed
          echo $NAR_NAME
          echo $OUTPUT

          nix copy --to file://`pwd`/${{ matrix.system }} --from ssh-ng://eu.nixbuild.net $OUTPUT --extra-experimental-features nix-command
          ls -la
          ls -la ${{ matrix.system }}
          ls -la ${{ matrix.system }}/nar
          tree ${{ matrix.system }}/nar
          cat ${{ matrix.system }}/nar/${NAR_NAME}.nar.xz | xz -dc | nix-store --restore ${{ matrix.system }}.${{ matrix.package }}
          tree
          ls -la
          ls -la ${{ matrix.system }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.system }}.${{ matrix.package }}
          path: ${{ matrix.system }}.${{ matrix.package }}

  create-docker-manifest:
    runs-on: ubuntu-latest
    needs: [download-docker-images]
    permissions: write-all
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ghcr.io/unionfi/uniond:${{ github.ref_name }}-aarch64-linux
      - run: docker pull ghcr.io/unionfi/uniond:${{ github.ref_name }}-x86_64-linux
      - run: |
          docker manifest create \
          ghcr.io/unionfi/uniond:${{ github.ref_name }} \
          --amend ghcr.io/unionfi/uniond:${{ github.ref_name }}-aarch64-linux \
          --amend ghcr.io/unionfi/uniond:${{ github.ref_name }}-x86_64-linux \
      - run: docker manifest push ghcr.io/unionfi/uniond:${{ github.ref_name }}
    
  release-candidate:
    runs-on: ubuntu-latest
    needs: [create-docker-manifest, download-static-binaries]
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -R
      - name: 'Create release candidate'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: '${{secrets.GITHUB_TOKEN}}'
          prerelease: true
          automatic_release_tag: latest-rc
          title: ${{github.ref_name}}
          files: |
            **/uniond



