name: ReleaseCandidate

on:
  push:
    tags: ['v[0-9]+\.[0-9]+\.[0-9]+\-rc[0-9]+']

jobs:
  build:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v16
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
    with:
      filter_builds: '((.top_attr == "packages") and (.system == "x86_64-linux" or .system == "aarch64-linux") and (.attr != "generate-evm-proto" and .attr != "generate-prover-proto" and .attr != "pre-commit-check" and .attr != "pre-commit" and .attr != "devnet")) or (.attr == "devnet" and .system == "x86_64-linux")'
  download-docker-images:
    runs-on: ubuntu-latest
    needs: [build]
    permissions: write-all
    strategy:
      matrix:
        system: [ aarch64-linux, x86_64-linux ]
    steps: 
      - uses: actions/download-artifact@v3
        with:
          name: packages.${{ matrix.system }}.uniond-image
      - uses: nixbuild/nix-quick-install-action@v22
      - uses: nixbuild/nixbuild-action@v17
        with:
          nixbuild_token: ${{ secrets.nixbuild_token }}
      - run: mkdir ${{ matrix.system }}
      - run: nix copy --to file://`pwd`/${{ matrix.system }} --from ssh-ng://eu.nixbuild.net `cat result.json | jq -r '.packages."${{ matrix.system }}"."uniond-image".outputs.out'` --extra-experimental-features nix-command
      - run: cat ${{ matrix.system }}/nar/*.nar.xz | xz -dc | nix-store --restore ${{ matrix.system }}.uniond-image
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.system}}.uniond-image
          path: ${{matrix.system}}.uniond-image
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker load < ${{ matrix.system }}.uniond-image
      - run: docker tag `docker images -q uniond` ghcr.io/unionfi/uniond:${{ github.ref_name }}-${{ matrix.system }}
      - run: docker push ghcr.io/unionfi/uniond:${{ github.ref_name }}-${{ matrix.system }}

  create-docker-manifest:
    runs-on: ubuntu-latest
    needs: [download-docker-images]
    permissions: write-all
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ghcr.io/unionfi/uniond:${{ github.ref_name }}-aarch64-linux
      - run: docker pull ghcr.io/unionfi/uniond:${{ github.ref_name }}-x86_64-linux
      - run: |
          docker manifest create \
          ghcr.io/unionfi/uniond:${{ github.ref_name }} \
          --amend ghcr.io/unionfi/uniond:${{ github.ref_name }}-aarch64-linux \
          --amend ghcr.io/unionfi/uniond:${{ github.ref_name }}-x86_64-linux \
      - run: docker manifest push ghcr.io/unionfi/uniond:${{ github.ref_name }}
    

  release-candidate:
    runs-on: ubuntu-latest
    needs: [download-docker-images]
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -R
      - name: 'Create release candidate'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: '${{secrets.GITHUB_TOKEN}}'
          prerelease: true
          automatic_release_tag: latest-rc
          title: ${{github.ref_name}}
          files: |
            **/*.uniond-image



