name: Deploy Site

on:
  push:
    branches:
    - main

env:
    ARTIFACT_NAME: BUILD_LOG
    NIX_VERSION: nix-2.14.1
    NIXPKGS_CHANNEL: nixos-22.11

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  deploy:
    # temporarily disable
    if: ${{ false }}
    runs-on: beefy-runner
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:${{ env.NIXPKGS_CHANNEL }}
          github_access_token: ${{ github.token }}
          extra_nix_config: |
            trusted-public-keys = union.cachix.org-1:TV9o8jexzNVbM1VNBOq9fu8NK+hL6ZhOyOh0quATy+M= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://union.cachix.org/ https://cache.nixos.org/
      - run: |
          nix-channel --add https://nixos.org/channels/${{ env.NIXPKGS_CHANNEL }} nixpkgs
          nix-channel --update
