# name: Deploy Site

# on:
#   push:
#     branches:
#     - main

# env:
#     ARTIFACT_NAME: BUILD_LOG
#     NIX_VERSION: nix-2.14.1
#     NIXPKGS_CHANNEL: nixos-22.11

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
#   cancel-in-progress: true

# jobs:
#   deploy:
#     runs-on: beefy-runner
#     permissions: write-all
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           lfs: true
#       - uses: cachix/install-nix-action@v20
#         with:
#           nix_path: nixpkgs=channel:${{ env.NIXPKGS_CHANNEL }}
#           github_access_token: ${{ github.token }}
#           extra_nix_config: |
#             trusted-public-keys = union.cachix.org-1:TV9o8jexzNVbM1VNBOq9fu8NK+hL6ZhOyOh0quATy+M= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
#             substituters = https://union.cachix.org/ https://cache.nixos.org/
#       - run: |
#           nix-channel --add https://nixos.org/channels/${{ env.NIXPKGS_CHANNEL }} nixpkgs
#           nix-channel --update
#           nix-env -iA nixpkgs.nodePackages.vercel
#       - name: "Publish Preview to Vercel"
#         id: publish-preview
#         run: |
#             cd site
#             export VERCEL_ORG_ID=team_lY7Vs9wFi3Ifb2A24bOxiA68
#             export VERCEL_PROJECT_ID=prj_HWQLgBiGFHNPSy5qJ3WpCeX1l492
#             vercel pull --yes --environment=production --token=${{secrets.VERCEL_TOKEN}} --scope unionbuild
#             vercel build --token=${{secrets.VERCEL_TOKEN}} --prod --scope unionbuild
#             vercel deploy --prebuilt --prod --token=${{secrets.VERCEL_TOKEN}} --scope unionbuild
   
